#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

(cd $FOAM_RUN/Case_Halfcar/Case && ./Allclean)

rm -rf motorBikeLES
cleanCase
#------------------------------------------------------------------------------
